# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update diff

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install igem-wikisync
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test something
      run: |
        git log --oneline
        git branch
        git status
    - name: Deploy to iGEM
      env:
        IGEM_USERNAME: ${{ secrets.IGEM_USERNAME }}
        IGEM_PASSWORD: ${{ secrets.IGEM_PASSWORD }}
      run: |
        git diff --name-only master~1 master | python upload.py
